### ISSUE TITLE
Missing gpiod_line_request_input_flags

### ISSUE THREAD

**Issue by splitice** [sombriks/node-libgpiod#11]
Without support for gpiod_line_request_input_flags (which perhaps should be an additional argument in the requestInputMode) its not possible to set a pull up or pull down on the line.

This is the only thing preventing this library from being almost a drop-in replacement (that I have noticed) for the capabilities offered by most sysfs based APIs.

**Comment by d-beamon** [comment]
Any plans for this?

**Comment by sombriks** [comment]
feature should be available on 0.4.0 Release, anyone able to test it please provide feedback. here.

**Comment by sombriks** [comment]
https://github.com/sombriks/node-libgpiod/pull/21

**Comment by splitice** [comment]
Nice! I can certainly test it this week.

**Comment by splitice** [comment]
From a usability / API perspective I would have that method called "requestInputFlags" as it does not set the mode of the GPIO as `requestInputMode` as does.

Other than that it seems to work as designed.

**Comment by sombriks** [comment]
> From a usability / API perspective I would have that method called "requestInputFlags" as it does not set the mode of the GPIO as `requestInputMode` as does.
> 
> Other than that it seems to work as designed.

That's nice!

we can enhance the API design in the upcoming 1.x version. it's done for now.
