### ISSUE TITLE
No longer compatible with libgpiod < 1.6.x

### ISSUE THREAD

**Issue by alejandroclaro** [sombriks/node-libgpiod#27]
The documentation states in the requirements that this should be compatible with libgpiod 1.x. However, since version 0.4 it's no longer compatible with libgpiod versions lower than 1.6.0

![image](https://github.com/sombriks/node-libgpiod/assets/6095662/b3c999dc-1071-4548-b114-57e1f292707d)

It would be nice its compatibility could be maintained since LTS versions of many distros, like Ubuntu 20.04, are still shipped with libgpiod 1.4.

If not possible, I recommend updating the documentation and clarify the minimum requirements.

**Comment by sombriks** [comment]
Hello @alejandroclaro , thank you for reporting this!
I think it is related to what @splitice was warning me about in #25 and indeed, i should add some kind of ifdef or something to make it possible to build node-libgpiod again  under older versions -- as long as it is 1.x

**Comment by sombriks** [comment]
Hello @alejandroclaro when you have a chance, please check if it works again with libgpiod versions prior to 1.5 series.

**Comment by alejandroclaro** [comment]
Thanks @sombriks !

I will test this today.

**Comment by alejandroclaro** [comment]
@sombriks  looks like everything is good now.

Thanks!
